apiVersion: v1
kind: Service
metadata:
  name: registration-app-service
  labels:
    app: registration-app
spec:
  type: NodePort
  selector:
    app: registration-app
  ports:
    - protocol: TCP
      port: 5000            # Service port
      targetPort: 5000      # Container port
      nodePort: 30007       # NodePort (can be accessed via localhost:30007)
